version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: app
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - vn_ultimate_network
    depends_on:
      - db

  db:
    image: mongo:7.0
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./docker/db/:/data/db
    networks:
      - vn_ultimate_network

networks:
  vn_ultimate_network:
    driver: bridge
